# Generated by Django 4.1.3 on 2023-05-31 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTagsCategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('order', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardTagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cardtagscategoriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CardContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.TextField()),
                ('card_description', models.TextField()),
                ('blender_mesh', models.FileField(null=True, upload_to=main.models.CardContentModel.mesh_content_path)),
                ('fbx_mesh', models.FileField(null=True, upload_to=main.models.CardContentModel.mesh_content_path)),
                ('preview_mesh', models.FileField(null=True, upload_to=main.models.CardContentModel.mesh_content_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='main.cardtagsmodel')),
            ],
        ),
    ]
