# Generated by Django 4.1.3 on 2023-05-16 16:55

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cardcontentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcontentmodel',
            name='textures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=main.models.CardContentModel.texture_content_path), null=True, size=None),
        ),
    ]
