# Generated by Django 4.1.3 on 2023-05-17 09:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cardcontentmodel_textures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcontentmodel',
            name='blender_mesh',
            field=models.FileField(null=True, upload_to=main.models.CardContentModel.mesh_content_path),
        ),
        migrations.AlterField(
            model_name='cardcontentmodel',
            name='fbx_mesh',
            field=models.FileField(null=True, upload_to=main.models.CardContentModel.mesh_content_path),
        ),
        migrations.AlterField(
            model_name='cardcontentmodel',
            name='preview_mesh',
            field=models.FileField(null=True, upload_to=main.models.CardContentModel.mesh_content_path),
        ),
    ]
