# Generated by Django 4.1.3 on 2023-05-31 18:10

import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.SmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'asset_tag_category',
                'verbose_name_plural': 'asset_tag_categories',
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.FileField(upload_to=content.models.Texture.content_path)),
            ],
            options={
                'verbose_name': 'texture',
                'verbose_name_plural': 'textures',
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.assettagcategory')),
            ],
            options={
                'verbose_name': 'asset_tag',
                'verbose_name_plural': 'asset_tags',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('blender_mesh', models.FileField(null=True, upload_to=content.models.Asset.content_path)),
                ('fbx_mesh', models.FileField(null=True, upload_to=content.models.Asset.content_path)),
                ('preview_mesh', models.FileField(null=True, upload_to=content.models.Asset.content_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='content.assettag')),
                ('textures', models.ManyToManyField(to='content.texture')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
            },
        ),
    ]
