# Generated by Django 4.2.2 on 2023-06-13 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assettag',
            options={'verbose_name': 'Asset Tag', 'verbose_name_plural': 'Asset Tags'},
        ),
        migrations.AlterModelOptions(
            name='assettagcategory',
            options={'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='texture',
            options={'verbose_name': 'Texture', 'verbose_name_plural': 'Textures'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
