# Generated by Django 4.2.2 on 2023-06-13 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_asset_options_alter_assettag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
