# Generated by Django 4.2.2 on 2023-06-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_asset_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('see_own', 'Can see own added assets'), ('see_others', 'Can see others added assets'), ('edit_own', 'Can edit own assets'), ('edit_others', 'Can edit others assets'), ('upload', 'Can upload assets')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
    ]
