# Generated by Django 4.2.2 on 2023-06-20 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_alter_asset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('see_own_assets', 'Can see own added assets'), ('see_others_assets', 'Can see others added assets'), ('edit_own_assets', 'Can edit own assets'), ('edit_others_assets', 'Can edit others assets'), ('upload_assets', 'Can upload assets')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AddField(
            model_name='asset',
            name='favorites',
            field=models.ManyToManyField(related_name='users_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
