# Generated by Django 4.2.3 on 2023-07-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_asset_options_asset_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('see_own', 'Can see own added assets'), ('see_others', 'Can see others added assets'), ('edit_own', 'Can edit own assets'), ('edit_others', 'Can edit others assets'), ('upload', 'Can upload assets')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
    ]
