# Generated by Django 4.2.3 on 2023-08-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_asset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_asset', to='content.asset')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_asset', to='content.asset')),
            ],
        ),
    ]
